export enum TYPE_PREFIXES {
  REQUEST = "REQUEST",
  SUCCESS = "SUCCESS",
  FAILURE = "FAILURE",
}

export const DEFAULT_PREFIXES: string[] = [TYPE_PREFIXES.REQUEST, TYPE_PREFIXES.FAILURE, TYPE_PREFIXES.SUCCESS];
